### ISSUE TITLE
Remove the ? in the URL when there are no optional parameters

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/gravify#13]
When no optional parameters are given, there is no need for the question mark at the end of the URL.

That question mark should not be in the returned URL value when no optional parameter values are given to the constructor.
___
_New contributors: This is in the `/gravify/__init__.py` file._
___
If you’d like to work on this, please comment here before you start so others don’t start on the same thing. Also, make sure to update the test file (`/tests/test_main.py`).

**Comment by widnyana** [comment]
hi @bsoyka, I would like to take this one

**Comment by anuragjain0610** [comment]
Hey! can I work on this one?

**Comment by bsoyka** [comment]
Sorry, @anuragjain0610, but another user started this before you. If you’d like, you can try another issue here with the “help wanted” label.
