### ISSUE TITLE
Colors of logo don't match

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/gravify#22]
This relates to #1 and #10. (@lucasvazq)
___
The colors of the logo do not match. The icon is #188DBF and the text below it is #4990E1. To fix this, the color of the text should be changed to match the color of the icon.
___
Please comment below before you start working on this, and when you are done, please make a PR targeting the `development` branch.

**Comment by AndrewJMD** [comment]
Mind if I take a moment and fix it?

**Comment by bsoyka** [comment]
@AndrewJMD Go ahead!

**Comment by lucasvazq** [comment]
Lool, HAHA 😂, 🙇‍♂️🤦🏻‍♂️

**Comment by bsoyka** [comment]
Opening this back up
