### ISSUE TITLE
Add support for a default image parameter

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/gravify#3]
https://en.gravatar.com/site/implement/images#default-image

**Comment by bsoyka** [comment]
Fixed in 0.0.3

**Comment by charanjit-singh** [comment]
We can define some static constants for predefined default values to make API more sensible.

```
Class Gravatar( )
     Type_404 = "404"
     Type_mystreyPerson. = "mp"

And so on
     
```

**Comment by bsoyka** [comment]
@charanjit-singh Would you like to work on this?

**Comment by bsoyka** [comment]
Created #24
