### ISSUE TITLE
Add support for a force default parameter

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/gravify#5]
https://en.gravatar.com/site/implement/images#force-default

Depends on #3

**Comment by charanjit-singh** [comment]
@bsoyka 
Why are we creating `url generator`  using `urllib.parse` if we can do easily by passing dict as GET params in [urllib.request](https://docs.python.org/3/library/urllib.request.html)

It'll solve problem of generating `?`s and '&`s in urls

**Comment by charanjit-singh** [comment]
It'll help [https://docs.python.org/3.1/howto/urllib2.html#data](https://docs.python.org/3.1/howto/urllib2.html#data)

**Comment by charanjit-singh** [comment]
or We can use

```
values = {'name' : 'Michael Foord',
          'location' : 'Northampton',
          'language' : 'Python' }

data = urllib.parse.urlencode(values)
```

**Comment by SimonJang** [comment]
If you want, I can help with this issue as well. Unless you want to keep the remaining 2 issues open as 'good first issue'.

**Comment by bsoyka** [comment]
You can certainly help if you’d like to!
