### ISSUE TITLE
Add support for a max rating parameter

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/gravify#6]
https://en.gravatar.com/site/implement/images#rating

**Comment by charanjit-singh** [comment]
On it

**Comment by bsoyka** [comment]
Thanks, @charanjit-singh!

**Comment by bsoyka** [comment]
@charanjit-singh When you make your changes, please make a pull request that merges them into the **`development`** branch.

**Comment by SimonJang** [comment]
@charanjit-singh you're still busy with this one? Otherwise I can pick up this issue.

**Comment by bsoyka** [comment]
@SimonJang If you're still up to the task, go for it! Make a PR into the `master` branch.

**Comment by SimonJang** [comment]
Ok, got some time this weekend anyway!
