### ISSUE TITLE
Check types and values when creating Gravatar instances

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/gravify#74]
Types and other constraints should be checked when initializing a `Gravatar` object. These constraints are all listed in the `Gravatar` class' docstring and just need to be implemented in code.

https://github.com/bsoyka/gravify/blob/86564faa42e2971c04495226ccbedabb070924f2/gravify/__init__.py#L17-L35

Please comment on this to let me know if you're interested in working on this!

**Comment by Edald123** [comment]
Hi! Can I try this issue? If yes, do I need to know anything else to start working on it?

**Comment by Edald123** [comment]
Thank you! I will be working on it.

**Comment by Edald123** [comment]
Hi, I already reviewed the code and I just want to confirm if my approach would be correct. I'm planning to use the decorator @property and its setter method to validate data types and values depending on the parameter. An example of the code to do this for the parameters  _**email and validate_email**_  would be:

`@property
    def email(self):
        return self._email

    """Validates string data type and value for email"""
    @email.setter
    def email(self, value):
        if isinstance(value, str):
            if self.verify_email and not validate_email(value):
                raise ValueError('Invalid email address')
            self._email = value
        raise ValueError('email must be string')
    
    @property
    def verify_email(self):
        return self._verify_email

    """Validates boolean data type for verify_email"""
    @verify_email.setter
    def verify_email(self, value):
        if isinstance(value, bool):
            self._verify_email = value
        raise ValueError('verify_email must be boolean')`

If you agree with this approach, it would be necessary to do this for all the parameters: email, verify_email, default_image, size, force_default, and max_rating. Would this be a good solution?

**Comment by bsoyka** [comment]
@Edald123 Looks pretty good to me! The only note that I have is that the docstrings should be inside the functions, but other than that it should work great.

Would you be able to add some tests for this new type checking or would you like me (or someone else) to?

**Comment by Edald123** [comment]
Great! I will change the docstrings and implement the rest. 
I can also implement the tests, the only thing that I would like to ask is how do you run your tests?
I was going to run: `python -m unittest tests/test_main.py` but when I run that it says: `Ran 0 tests`.

**Comment by bsoyka** [comment]
The tests are run with [`pytest`](https://docs.pytest.org/en/6.2.x/) - just need to run the following:

```sh
$ python -m pip install pytest
$ pytest
```

**Comment by Edald123** [comment]
Thank you!, I'm on it.

**Comment by Edald123** [comment]
Hi! I have already implemented the methods for all the required validations for types and values. I'm working on the tests and I have 2 questions:
1. Should I allow the default values of the constructor to be accepted for the class Gravatar or is it ok to force the correct values and datatypes always, so it would be necessary to always send the correct data types and values? 
2. Should I implement the tests in test_main.py or should I create another file for those in the tests folder?

When running the tests with `pytest` I was having a ModuleNotFoundError, I fixed it by adding an empty file __init__.py in the tests folder. Should I leave it like that or change it?

**Comment by bsoyka** [comment]
@Edald123 Hey!

1. Yep, try to use the same defaults from the current `__init__` method. I want to keep backward compatibility here and I don't want to require every single parameter.
2. Either one works!
3. If that works, go for it! I've just done `pip install -e .` in the repo directory for myself.

**Comment by Edald123** [comment]
Thank you! using that  `pip install -e .` allowed me to delete the __init__.py that I created and run the tests correctly, I will be sharing my PR soon.

**Comment by Edald123** [comment]
Hi @bsoyka I have finished the implementation of all validations and also I created all tests. 

Once you answer my last question I can make my PR. 

Thank you!

**Comment by bsoyka** [comment]
Hey, @Edald123! You can just change the test to expect the error - I think I'd rather have an error than just ignore the bad value.

**Comment by Edald123** [comment]
Perfect, I think I have made the correct changes, I have made my PR, please let me know if anything needs to be changed.
